const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/adminCustomerController');
const { verifyAdminToken, requirePermission } = require('../middleware/authMiddleware');
router.get('/', verifyAdminToken, requirePermission('customers', 'view'), ctrl.getAll);
router.get('/:id', verifyAdminToken, requirePermission('customers', 'view'), ctrl.getOne);
router.get('/:id/login-logs', verifyAdminToken, requirePermission('customers', 'view'), ctrl.getLogs);
router.put('/:id/status', verifyAdminToken, requirePermission('customers', 'edit'), ctrl.updateStatus);
router.delete('/:id', verifyAdminToken, requirePermission('customers', 'delete'), ctrl.deleteCustomer);
module.exports = router;
